name: deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - run: npm ci

      - run: npm run type-check
      - run: npm run lint
      - run: npm run test

      - run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken:    ${{ secrets.CF_API_TOKEN }}
          accountId:   ${{ secrets.CF_ACCOUNT_ID }}
          command:     pages deploy dist --project-name=barbora-cv --branch=main
